---
title: "toggl-projects"
author: "bosse"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## toggl projects


```{r init, include=FALSE}
#  install.packages("tidyverse")
library(tidyverse)
#  install.packages("jsonlite")
library(jsonlite)
# install.package("httr")
library(httr)

if(Sys.getenv("TOGGL_TOKEN") == "" || Sys.getenv("TOGGL_WORKSPACE") == "") {
  stop("Missing Environment Variables: TOGGL_TOKEN or TOGGL_WORKSPACE")
}

togglToken <- Sys.getenv("TOGGL_TOKEN")
togglWid   <- Sys.getenv("TOGGL_WORKSPACE")

getClients <- function(token, wid, verbose = FALSE) {
  username <- token
  password <- "api_token"


  base <- "https://toggl.com/api"
  endpoint <- "v8/workspaces"
  what <- "clients"

  call <- paste(base,endpoint,wid,what, sep="/")

  if(verbose) {
    result <- GET(call, authenticate(username,password), verbose())
  } else {
    result <- GET(call, authenticate(username,password))
  }
  return(result)
}

getProjects <- function(token, cid, verbose = FALSE) {
  username <- token
  password <- "api_token"


  base <- "https://toggl.com/api"
  endpoint <- "v8/clients"
  what <- "projects"

  call <- paste(base,endpoint,cid,what, sep="/")

  if(verbose) {
    result <- GET(call, authenticate(username,password), verbose())
  } else {
    result <- GET(call, authenticate(username,password))
  }

  return(result)
}

projectPlot <- function(data, name) {
  # ToDo: check if data contains estimated_hours, colnames()
  v1 <- ggplot(data=data) +
    theme(axis.text.x = element_text(angle = 25, hjust = 1, size = 8)) +
    labs(x=NULL, y="Hours", title=name, caption="data from toggl")

  if ("actual_hours" %in% colnames(data)) {
    v1 <- v1 + geom_col(aes(
      x=name,
      y=actual_hours,
      fill=hex_color),
      color = "Black", 
      show.legend = FALSE)
  }
  if ("estimated_hours" %in% colnames(data)) {
    v1 <- v1 + geom_point(aes(x=name, y=estimated_hours),
                          shape = 3, size = 2)
  }

  return(v1)
}
```

```{r clients, echo=FALSE}
clientsJSON <- getClients(togglToken, togglWid)

clients <- as.tibble(fromJSON(content(clientsJSON, "text")))
clients <- arrange(clients, name)
```
## Projects


```{r projects, echo=FALSE, warning=FALSE}
if(nrow(clients) > 0) {
  for (row in 1:nrow(clients)) {
    cId <- clients[row, "id" ][[1]]
    cName <- clients[row, "name"][[1]]

    #print(paste(cId, cName))
    t1 <- Sys.time()
    projectsJSON <- getProjects(togglToken, cId)
    projects <- as.tibble(fromJSON(content(projectsJSON, "text")))
    p1 <- projectPlot(projects, cName)
    plot(p1)
    
    if(Sys.time()-t1 < 1) {
      Sys.sleep(1)
    }
  }
}
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
